import fs from "fs";
import path from "path";
import yaml from "js-yaml";
import kc from "../kube/client.js";

/**
 * Get current cluster info from kube-api (NO kubectl)
 */
function clusterInfo() {
  const cluster = kc.getCurrentCluster();

  if (!cluster) {
    throw new Error("No active Kubernetes cluster found in kubeconfig");
  }

  return {
    name: cluster.name,
    server: cluster.server,
    ca: cluster.caData
  };
}

/**
 * Generate kubeconfig for CERT-based USER
 * - Secure by default
 * - Includes commented insecure-skip-tls-verify template
 */
export function generateUserKubeconfig(username, certDir) {
  const cluster = clusterInfo();

  const certPath = path.join(certDir, `${username}.crt`);
  const keyPath = path.join(certDir, `${username}.key`);

  const clientCertData = fs.readFileSync(certPath).toString("base64");
  const clientKeyData = fs.readFileSync(keyPath).toString("base64");

  const kubeconfig = {
    apiVersion: "v1",
    kind: "Config",
    clusters: [
      {
        name: cluster.name,
        cluster: {
          server: cluster.server,
          "certificate-authority-data": cluster.ca
        }
      }
    ],
    users: [
      {
        name: username,
        user: {
          "client-certificate-data": clientCertData,
          "client-key-data": clientKeyData
        }
      }
    ],
    contexts: [
      {
        name: `${username}@${cluster.name}`,
        context: {
          cluster: cluster.name,
          user: username
        }
      }
    ],
    "current-context": `${username}@${cluster.name}`
  };

  const kubeconfigDir = path.join(process.env.RABC_DATA_DIR, "kubeconfigs");
  fs.mkdirSync(kubeconfigDir, { recursive: true });

  const kubeconfigPath = path.join(kubeconfigDir, `${username}.yaml`);

  const yamlBody = yaml.dump(kubeconfig, { noRefs: true });

  // 🔐 COMMENTED TLS TEMPLATE (SECURE DEFAULT)
  const comments = `# =====================================================
# Generated by RABC
# User Kubeconfig
# User: ${username}
# =====================================================
#
# 🔐 TLS SECURITY NOTES:
# - This kubeconfig uses certificate-authority-data (SECURE DEFAULT)
# - If your cluster uses self-signed certs and you face TLS issues,
#   you MAY uncomment the option below AT YOUR OWN RISK:
#
# clusters:
# - cluster:
#     server: ${cluster.server}
#     insecure-skip-tls-verify: true
#
# ⚠️ WARNING:
# - Disabling TLS verification is NOT recommended for production
# - Use only for testing or isolated environments
#
# =====================================================

`;

  fs.writeFileSync(kubeconfigPath, comments + yamlBody);

  return kubeconfigPath;
}

/**
 * Generate kubeconfig for SERVICE ACCOUNT (token-based)
 * - Secure by default
 * - Includes commented insecure-skip-tls-verify template
 */
export function generateSAKubeconfig(saName, namespace, token) {
  const cluster = clusterInfo();

  const kubeconfig = {
    apiVersion: "v1",
    kind: "Config",
    clusters: [
      {
        name: cluster.name,
        cluster: {
          server: cluster.server,
          "certificate-authority-data": cluster.ca
        }
      }
    ],
    users: [
      {
        name: `${saName}-${namespace}`,
        user: { token }
      }
    ],
    contexts: [
      {
        name: `${saName}@${cluster.name}`,
        context: {
          cluster: cluster.name,
          user: `${saName}-${namespace}`,
          namespace
        }
      }
    ],
    "current-context": `${saName}@${cluster.name}`
  };

  const kubeconfigDir = path.join(process.env.RABC_DATA_DIR, "kubeconfigs");
  fs.mkdirSync(kubeconfigDir, { recursive: true });

  const kubeconfigPath = path.join(
    kubeconfigDir,
    `sa-${saName}-${namespace}.yaml`
  );

  const yamlBody = yaml.dump(kubeconfig, { noRefs: true });

  const comments = `# =====================================================
# Generated by RABC
# Service Account Kubeconfig
# ServiceAccount: ${saName}
# Namespace: ${namespace}
# =====================================================
#
# 🔐 TLS SECURITY NOTES:
# - This kubeconfig uses certificate-authority-data (SECURE DEFAULT)
# - If your cluster uses self-signed certs and you face TLS issues,
#   you MAY uncomment the option below AT YOUR OWN RISK:
#
# clusters:
# - cluster:
#     server: ${cluster.server}
#     insecure-skip-tls-verify: true
#
# ⚠️ WARNING:
# - Disabling TLS verification is NOT recommended for production
#
# =====================================================

`;

  fs.writeFileSync(kubeconfigPath, comments + yamlBody);

  return kubeconfigPath;
}
